### ISSUE TITLE
TypeNotPresentException with embulk 0.11.0

### ISSUE THREAD

**Issue by shin1103** [hito4t/embulk-input-jdbc-external#3]
I faced this [ISSUE](https://github.com/embulk/embulk-input-jdbc/issues/257). So, I'd like to use `embulk-input-oracle` , but these error was occurs in this environment.

# ENV
* embulk-0.11.0
* embulk-input-oracle-0.11.1
* JVM: Correttto-8.392.08.1
* Oracle: 21c Express Edition Release 2
* Target Table Columns: 
  * CHAR(1)
  * NUMBER(5, 0)
  * VARCHAR2(25)
  * NUMBER (9,4)
  * DATE
  * VARCHAR2(10)
  * NUMBER(7, 0)
  * VARCHAR2(3)

# TO REPRODUCE
Set datasource oracle and set schema.
```yml
in:
    type: oracle
    driver_path: ./jdbc8.jar
    host: XXXXXX
    port: XXXXXX
    database: XXXXXX
    user: XXXXX
    password: XXXXX
    schema: my_schema
    table: my_table
```

# ERROR LOG
```log
[ec2-user@ip-111-111-111-111 docker] java -jar /home/ec2-user/.embulk/bin/embulk preview config.ora.yml
2024-03-04 02:41:27.101 +0000 [INFO] (main): embulk home is set by the location of embulk-properties found in: /home/ec2-user/.embulk
2024-03-04 02:41:27.120 +0000 [INFO] (main): m2_repo is set as a sub directory of embulk home: /home/ec2-user/.embulk/lib/m2/repository
2024-03-04. 02:41:27.121 +0808 [INFO] (main): gem_home is set as a sub directory of embulk home: /home/ec2-user/-embulk/lib/gems
2024-03-04 02:41:27.122 +0000 [INFO] (main): gem path is set empty.
2024-93-04 02:41:27.123 +0000 [DEBUG] (main): Embulk systen property "default guess plugin* is set to: "gzip, bzip2, json, csv"
2024-03-04 02:41:27.550 +0000 [INFO] (main): Started Embulk v0.11.0
2024-03-04 02:41:34.517 +0000 [INFO] (0001: preview): Gen's home and path are set by system configs "gen home": */home/ec2-user/embulk/lib/gens", "gem path": *
2824-03-84 02:41:37.215 +0000 [INFO] (0001:preview): Loaded JRuby runtime 9.4.5.0
2024-03-04 02:41:37.408 +0000 [INFO] (0001: preview): Loaded plugin embulk-input-oracle (0.11.1)
org.embulk.config.ConfigException: java.lang-TypeNotPresentException: Type com.fasterxml.jackson.databind.JsonNode not present at ong. embulk.deps.config.ModelManagerDelegateImpl.readObjectwithConfigSerDe(ModelManagerDelegateImp].java:97)
at org.enbulk.deps. config-DataSourceImp1.loadConfig(DataSourceImpl.java:335)
at org.embulk.input.jdbc.AbstractJdbcInputPlugin.transaction(AbstractJdbcInputPlugin.java:187)
at org-embulk.exec.PreviewExecutor.doPreview(PreviewExecutor.java:119) at org.embulk.exec.PreviewExecutor.doPreview(PreviewExecutor.java:102)
at org.embulk.exec.PreviewExecutor.access$000(PreviewExecutor-java:31)
at org-embulk.exec.PreviewExecutor$1.run(PreviewExecutor-java:69) at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:66)
at org-embulk.spi.ExecInternal.doWith(ExecInternal.java:26)
at org.embulk.exec.PreviewExecutor.preview(PreviewExecutor-java:66)
at org-embulk.EmbulkEmbed.preview(EmbulkEmbed.java: 267)
at org.embulk.EmbulkRunner-previewInternal(EmbulkRunner-java:212)
at org.embulk.EmbulkRunner-preview(EmbulkRunner-java:164)
at org-embulk.cl1.EmbulkRun.runInternal(EmbulkRun.java:105)
at org-embulk.c11.EmbulkRun. run(EmbulkRun.java:24)
at org-embulk.cli.Main-main(Main.java:53)
Caused by: java.lang-TypeNotPresentException: Type com. fasterxml.jackson.databind.IsonNode not present

Caused by: java. lang-TypeNotPresentException: Type com. fasterxml.jackson.databind.JsonNode not present
at sun.reflect.genenics.factory. CoreReflectionFactory-makeNamedType(CoreReflectionFactory.Java: 117)
at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature Reifier-java:125) at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier-java:138)
at sun.reflect.generics.tree.ClassTypeSignature.accept/ClassTypeSignature.java:49)
at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier. java:68)
sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
at sun.reflect.generics.repository.MethodRepository-getReturnType(MethodRepository-java:68)
at java. lang.reflect.Method.getGenericReturnType(Method.java:255)
at org. embulk.deps.config.TaskSerDe$TaskDeserializer-getterMappings(TaskSerDe.java:91)
at org-embulk.deps.config-TaskSerDe$TaskDeserializer.<init>(TaskSerDe.java:82)
at org.embulk.deps.config.TaskSerDe$ConfigTaskDeserializer.<init>(TaskSerDe.java:245)
at org.embulk.deps.config-TaskSerDe$ConfigTaskDeserializerModule.newTaskDeserializer(TaskSerDe.java: 324)
at org.embulk.deps.config.TaskSerDeSTaskDeserializerModule$1. findBeanDeserializer(TaskSerDe.java: 298)
at com. fasterxml. jackson.databind.deser.BasicDeserializerFactory._findCustomBeanDeserializerBasicDeserializerFactory-java: 1624) at com.fasterxml. jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory-java: 335) at com. fasterml, jackson.databind deser DesertalizerCache._createDeserializer2(DeserializerCache. java:403) at com.fasterml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java: 352)
at com. fasterml. jackson.databind.desen DeserializerCache._createAndCache2(DeserializerCache,java:264)
at com.fasterxml.jackson.databind.deser.DeserializerCache./
createAndCacheValueDeserializer(Deserialize Cache. java: 244)
com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
com. fasterxml. jackson.databind.DeserializationContext. findRootValueDeserializer(DeserializationContext.java:461)
com. fasterxml.jackson.databind.ObjectMapper. _findRootDeserializer (ObjectMapper. java:3838)
com. fasterxm1. jackson.databind.objectMapper _readvalue(ObjectMapper.java:3703)
com.fasterxml. jackson.databind.ObjectMapper.readValue(ObjectMapper-java:2005)
at org. embulk, deps. config-Mode IManagerDelegateImpl.readobjectwithConfigSerDe(ModelManagerDelegateImpl. java:92)
15 more
Caused by: java. lang.ClassNotFoundException: com.fasterxml.jackson.databind.JsonNode at org.embulk.plugin.PluginClassLoader.loadClass(PluginClassLoader-java:160)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
at java.lang.Class. forName®(Native Method) at java. lang-Class. forName(Class.java: 348)
at sun.reflect.generics.factory.CoreReflectionFactory-makeNamedType(CoreReflectionFactory-java:114)
42 more

Error: java. lang-TypeNotPresentException: Type com.fasterxml.jackson.databind.JsonNode not present
```

**Comment by hito4t** [comment]
@shin1103 
Thank you for the report. And I'm sorry for the late reply.
I've updated embulk-input-oracle and it will work with embulk 0.11 .

**Comment by s-furu** [comment]
@hito4t 
Thank you for the update!
But the same error occurred in the following environment.
* embulk-0.11.5
* embulk-input-oracle-0.11.1
* JRuby runtime 9.3.15.0
*  embulk-output-bigquery (0.7.3)

Embulk-input-oracle seems to be [latest version](https://rubygems.org/gems/embulk-input-oracle/versions/0.11.1-java).
Doesn't embulk-input-oracle-0.11.1 support embulk-0.11.5?

**Comment by hito4t** [comment]
@s-furu 
embulk-input-oracle-0.11.1 doesn't support embulk-0.11.5 .
The latest sources support it, but I haven't released yet.
Could you build from the latest source?

**Comment by s-furu** [comment]
@hito4t 
It worked with the latest source (marked as embulk-input-oracle 0.14.0)!
I hope it would be released in rubygems soon. Thank you so much!

**Comment by kakoni** [comment]
@hito4t Hi! Could you push the 0.14.0 to rubygems?
